
DROP TABLE IF EXISTS currencies;
CREATE TABLE IF NOT EXISTS currencies (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  `code` varchar(10) NOT NULL,
  `name` varchar(300) NOT NULL,
  display_order int(11) NOT NULL DEFAULT '3',
  PRIMARY KEY (id)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=168 ;

INSERT INTO currencies (id, code, name, display_order) VALUES
(1, 'USD', 'US Dollar', 1),
(2, 'EUR', 'Euro', 1),
(3, 'GBP', 'British Pound', 1),
(4, 'INR', 'Indian Rupee', 2),
(5, 'AUD', 'Australian Dollar', 2),
(6, 'CAD', 'Canadian Dollar', 2),
(7, 'SGD', 'Singapore Dollar', 2),
(8, 'CHF', 'Swiss Franc', 2),
(9, 'MYR', 'Malaysian Ringgit', 2),
(10, 'JPY', 'Japanese Yen', 2),
(11, 'CNY', 'Chinese Yuan Renminbi', 1),
(12, 'NZD', 'New Zealand Dollar', 2),
(13, 'THB', 'Thai Baht', 3),
(14, 'HUF', 'Hungarian Forint', 3),
(15, 'AED', 'Emirati Dirham', 3),
(16, 'HKD', 'Hong Kong Dollar', 3),
(17, 'MXN', 'Mexican Peso', 3),
(18, 'ZAR', 'South African Rand', 3),
(19, 'PHP', 'Philippine Peso', 3),
(20, 'SEK', 'Swedish Krona', 3),
(21, 'IDR', 'Indonesian Rupiah', 3),
(22, 'SAR', 'Saudi Arabian Riyal', 3),
(23, 'BRL', 'Brazilian Real', 3),
(24, 'TRY', 'Turkish Lira', 3),
(25, 'KES', 'Kenyan Shilling', 2),
(26, 'KRW', 'South Korean Won', 3),
(27, 'EGP', 'Egyptian Pound', 2),
(28, 'IQD', 'Iraqi Dinar', 3),
(29, 'NOK', 'Norwegian Krone', 3),
(30, 'KWD', 'Kuwaiti Dinar', 3),
(31, 'RUB', 'Russian Ruble', 3),
(32, 'DKK', 'Danish Krone', 3),
(33, 'PKR', 'Pakistani Rupee', 3),
(34, 'ILS', 'Israeli Shekel', 3),
(35, 'PLN', 'Polish Zloty', 3),
(36, 'QAR', 'Qatari Riyal', 3),
(37, 'XAU', 'Gold Ounce', 3),
(38, 'OMR', 'Omani Rial', 3),
(39, 'COP', 'Colombian Peso', 3),
(40, 'CLP', 'Chilean Peso', 3),
(41, 'TWD', 'Taiwan New Dollar', 3),
(42, 'ARS', 'Argentine Peso', 3),
(43, 'CZK', 'Czech Koruna', 3),
(44, 'VND', 'Vietnamese Dong', 3),
(45, 'MAD', 'Moroccan Dirham', 3),
(46, 'JOD', 'Jordanian Dinar', 3),
(47, 'BHD', 'Bahraini Dinar', 3),
(48, 'XOF', 'CFA Franc', 3),
(49, 'LKR', 'Sri Lankan Rupee', 3),
(50, 'UAH', 'Ukrainian Hryvnia', 3),
(51, 'NGN', 'Nigerian Naira', 3),
(52, 'TND', 'Tunisian Dinar', 3),
(53, 'UGX', 'Ugandan Shilling', 2),
(54, 'RON', 'Romanian New Leu', 3),
(55, 'BDT', 'Bangladeshi Taka', 3),
(56, 'PEN', 'Peruvian Nuevo Sol', 3),
(57, 'GEL', 'Georgian Lari', 3),
(58, 'XAF', 'Central African CFA Franc BEAC', 3),
(59, 'FJD', 'Fijian Dollar', 3),
(60, 'VEF', 'Venezuelan Bolivar', 3),
(61, 'BYR', 'Belarusian Ruble', 3),
(62, 'HRK', 'Croatian Kuna', 3),
(63, 'UZS', 'Uzbekistani Som', 3),
(64, 'BGN', 'Bulgarian Lev', 3),
(65, 'DZD', 'Algerian Dinar', 3),
(66, 'IRR', 'Iranian Rial', 3),
(67, 'DOP', 'Dominican Peso', 3),
(68, 'ISK', 'Icelandic Krona', 3),
(69, 'XAG', 'Silver Ounce', 3),
(70, 'CRC', 'Costa Rican Colon', 3),
(71, 'SYP', 'Syrian Pound', 3),
(72, 'LYD', 'Libyan Dinar', 3),
(73, 'JMD', 'Jamaican Dollar', 3),
(74, 'MUR', 'Mauritian Rupee', 3),
(75, 'GHS', 'Ghanaian Cedi', 3),
(76, 'AOA', 'Angolan Kwanza', 3),
(77, 'UYU', 'Uruguayan Peso', 3),
(78, 'AFN', 'Afghan Afghani', 3),
(79, 'LBP', 'Lebanese Pound', 3),
(80, 'XPF', 'CFP Franc', 3),
(81, 'TTD', 'Trinidadian Dollar', 3),
(82, 'TZS', 'Tanzanian Shilling', 2),
(83, 'ALL', 'Albanian Lek', 3),
(84, 'XCD', 'East Caribbean Dollar', 3),
(85, 'GTQ', 'Guatemalan Quetzal', 3),
(86, 'NPR', 'Nepalese Rupee', 3),
(87, 'BOB', 'Bolivian Boliviano', 3),
(88, 'ZWD', 'Zimbabwean Dollar', 3),
(89, 'BBD', 'Barbadian or Bajan Dollar', 3),
(90, 'CUC', 'Cuban Convertible Peso', 3),
(91, 'LAK', 'Lao or Laotian Kip', 3),
(92, 'BND', 'Bruneian Dollar', 3),
(93, 'BWP', 'Botswana Pula', 3),
(94, 'HNL', 'Honduran Lempira', 3),
(95, 'PYG', 'Paraguayan Guarani', 3),
(96, 'ETB', 'Ethiopian Birr', 2),
(97, 'NAD', 'Namibian Dollar', 3),
(98, 'PGK', 'Papua New Guinean Kina', 3),
(99, 'SDG', 'Sudanese Pound', 2),
(100, 'MOP', 'Macau Pataca', 3),
(101, 'NIO', 'Nicaraguan Cordoba', 3),
(102, 'BMD', 'Bermudian Dollar', 3),
(103, 'KZT', 'Kazakhstani Tenge', 3),
(104, 'PAB', 'Panamanian Balboa', 3),
(105, 'BAM', 'Bosnian Convertible Marka', 3),
(106, 'GYD', 'Guyanese Dollar', 3),
(107, 'YER', 'Yemeni Rial', 3),
(108, 'MGA', 'Malagasy Ariary', 3),
(109, 'KYD', 'Caymanian Dollar', 3),
(110, 'MZN', 'Mozambican Metical', 3),
(111, 'RSD', 'Serbian Dinar', 3),
(112, 'SCR', 'Seychellois Rupee', 3),
(113, 'AMD', 'Armenian Dram', 3),
(114, 'SBD', 'Solomon Islander Dollar', 3),
(115, 'AZN', 'Azerbaijani New Manat', 3),
(116, 'SLL', 'Sierra Leonean Leone', 3),
(117, 'TOP', 'Tongan Pa''anga', 3),
(118, 'BZD', 'Belizean Dollar', 3),
(119, 'MWK', 'Malawian Kwacha', 3),
(120, 'GMD', 'Gambian Dalasi', 3),
(121, 'BIF', 'Burundian Franc', 3),
(122, 'SOS', 'Somali Shilling', 3),
(123, 'HTG', 'Haitian Gourde', 3),
(124, 'GNF', 'Guinean Franc', 3),
(125, 'MVR', 'Maldivian Rufiyaa', 3),
(126, 'MNT', 'Mongolian Tughrik', 3),
(127, 'CDF', 'Congolese Franc', 3),
(128, 'STD', 'Sao Tomean Dobra', 3),
(129, 'TJS', 'Tajikistani Somoni', 3),
(130, 'KPW', 'North Korean Won', 3),
(131, 'MMK', 'Burmese Kyat', 3),
(132, 'LSL', 'Basotho Loti', 3),
(133, 'LRD', 'Liberian Dollar', 3),
(134, 'KGS', 'Kyrgyzstani Som', 3),
(135, 'GIP', 'Gibraltar Pound', 3),
(136, 'XPT', 'Platinum Ounce', 3),
(137, 'MDL', 'Moldovan Leu', 3),
(138, 'CUP', 'Cuban Peso', 3),
(139, 'KHR', 'Cambodian Riel', 3),
(140, 'MKD', 'Macedonian Denar', 3),
(141, 'VUV', 'Ni-Vanuatu Vatu', 3),
(142, 'MRO', 'Mauritanian Ouguiya', 3),
(143, 'ANG', 'Dutch Guilder', 3),
(144, 'SZL', 'Swazi Lilangeni', 3),
(145, 'CVE', 'Cape Verdean Escudo', 3),
(146, 'SRD', 'Surinamese Dollar', 3),
(147, 'XPD', 'Palladium Ounce', 3),
(148, 'SVC', 'Salvadoran Colon', 3),
(149, 'BSD', 'Bahamian Dollar', 3),
(150, 'XDR', 'IMF Special Drawing Rights', 3),
(151, 'RWF', 'Rwandan Franc', 2),
(152, 'AWG', 'Aruban or Dutch Guilder', 3),
(153, 'DJF', 'Djiboutian Franc', 3),
(154, 'BTN', 'Bhutanese Ngultrum', 3),
(155, 'KMF', 'Comoran Franc', 3),
(156, 'WST', 'Samoan Tala', 3),
(157, 'SPL', 'Seborgan Luigino', 3),
(158, 'ERN', 'Eritrean Nakfa', 3),
(159, 'FKP', 'Falkland Island Pound', 3),
(160, 'SHP', 'Saint Helenian Pound', 3),
(161, 'JEP', 'Jersey Pound', 3),
(162, 'TMT', 'Turkmenistani Manat', 3),
(163, 'TVD', 'Tuvaluan Dollar', 3),
(164, 'IMP', 'Isle of Man Pound', 3),
(165, 'GGP', 'Guernsey Pound', 3),
(166, 'ZMW', 'Zambian Kwacha', 3),
(167, 'SSP', 'South Sudanese Pound', 0);